[general]
import = ["~/.config/alacritty/rose-pine.toml"]

[window]
opacity = 0.9
padding = { x = 0, y = 0 }
dynamic_padding = true
#decorations = "None"

[env]
TERM = "xterm-256color"

[font]
#normal = { family = "FiraCode Nerd Font", style = "Semibold" }
#size = 10
normal = { family = "ComicMono Nerd Font", style = "Bold" }
size = 10.4
